jobs:
- job: Build
  #pool:
  #  vmImage: ubuntu-latest      
  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        # Write your PowerShell commands here.            
        Write-Host "Hello World ajtraining "
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        # Write your PowerShell commands here.
        
        Write-Host "Hello World $(project) "